env: "dev" #available envs: "dev", "prod"
db:
  username: "themaxs"
  password: "1234"
  host: "localhost"
  port: "5432"
  database: "e_commerce"
  ssl_mode: "disable"

app:
  serv_host: "localhost"
  serv_port: "7777"
  serv_username: "banger"
  serv_password: "4321"
  rw_timeout: 4s
  idle_timeout: 60s