env: "dev" #available envs: "dev", "prod"
db:
  username: "Your_name"
  password: "your_password"
  host: "localhost"
  port: "5432"
  database: "e_commerce"
  ssl_mode: "disable"

app:
  serv_host: "localhost"
  serv_port: "7777"
  serv_username: "username"
  rw_timeout: 4s
  idle_timeout: 60s